
# SEO settings
title: "PyAugusta"
title2: "" # default: ""
description: "A Python user group in Augusta, GA."
keywords: "Python Augusta"
url: "https://pyaugusta.github.io/" # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

# google_analytics: UA-XXXXX-XX
# repo: http://github.com/heiswayi/thinkspace
disqus_shortname: johnfmarion
twitter_username: pyaugusta
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Cory Taylor"
  job      : "Software Engineer"
  bio      : "I am a person."
  thumb    : /images/author.jpg
  # email    : hnrird@gmail.com
  # url      : http://heiswayi.github.io
  # github   : http://github.com/heiswayi
  # twitter  : http://twitter.com/HeiswayiNrird
  # facebook : https://www.facebook.com/heiswayi.nrird
  # linkedin : http://linkedin.com/in/nrird

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@pyaugusta"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
